services:
  server-1:
    container_name: app-instance-1
    build: app/java
    ports:
      - "5001:5000"
  server-2:
    container_name: app-instance-2
    build: app/java
    ports:
      - "5002:5000"
  loadbalancer_python:
    container_name: load-balancer-python
    build: loadbalancer/python
    ports:
      - "8080:5000"
  loadbalancer_java:
    container_name: load-balancer-java
    build: loadbalancer/java
    ports:
      - "8081:8080"
  benchmark:
    container_name: benchmark
    build: benchmark
    ports:
      - "8082:5000"
  loadbalancer_nginx:
    container_name: load-balancer-nginx
    image: nginx:1.21.6
    volumes:
      - ./loadbalancer/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8083:80"
