services:
  server-1:
    container_name: app-instance-1
    build: app
  server-2:
    container_name: app-instance-2
    build: app
  loadbalancer_python:
    container_name: load-balancer-python
    build: loadbalancer_python
    ports:
      - "8080:5000"
  loadbalancer_java:
    container_name: load-balancer-java
    build: loadbalancer_java
    ports:
      - "8081:8080"
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8082:80"
